# Generated by Django 5.1.4 on 2025-01-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen_1', models.ImageField(upload_to='productos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_4', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_5', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('video_url', models.CharField(max_length=200)),
                ('cantidad_me_gusta', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('enlace_detalles', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible')], default='Disponible', max_length=20)),
                ('categoria', models.CharField(choices=[('Venta', 'Venta'), ('Arriendo', 'Arriendo')], default='Venta', max_length=10)),
                ('procesos', models.CharField(choices=[('MEZCLA', 'Mezcla'), ('COMPACTACION', 'Compactación'), ('VIBRADORES', 'Vibradores'), ('DEMOLEDORA', 'Demoledora'), ('ALISADOR', 'Alisador'), ('CORTE', 'Corte'), ('ELEVACION', 'Elevación'), ('CARGA', 'Carga'), ('EQUIPOS_ESPECIALES', 'Equipos Especiales'), ('GENERADOR', 'Generador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Alisador',
                'verbose_name_plural': 'Tipos de Alisador',
            },
        ),
        migrations.CreateModel(
            name='TipoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Carga',
                'verbose_name_plural': 'Tipos de Carga',
            },
        ),
        migrations.CreateModel(
            name='TipoCompactacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Compactación',
                'verbose_name_plural': 'Tipos de Compactación',
            },
        ),
        migrations.CreateModel(
            name='TipoCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Corte',
                'verbose_name_plural': 'Tipos de Corte',
            },
        ),
        migrations.CreateModel(
            name='TipoDemoledor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Demoledor',
                'verbose_name_plural': 'Tipos de Demoledor',
            },
        ),
        migrations.CreateModel(
            name='TipoElevacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Elevación',
                'verbose_name_plural': 'Tipos de Elevación',
            },
        ),
        migrations.CreateModel(
            name='TipoEquiposEspeciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo Especial',
                'verbose_name_plural': 'Tipos de Equipos Especiales',
            },
        ),
        migrations.CreateModel(
            name='TipoGenerador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Generador',
                'verbose_name_plural': 'Tipos de Generador',
            },
        ),
        migrations.CreateModel(
            name='TipoMezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Mezcla',
                'verbose_name_plural': 'Tipos de Mezcla',
            },
        ),
        migrations.CreateModel(
            name='TipoVibrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Vibrador',
                'verbose_name_plural': 'Tipos de Vibrador',
            },
        ),
        migrations.CreateModel(
            name='Alisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipoalisador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('implementos', models.CharField(max_length=100)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipocarga')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compactacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tamaño', models.CharField(max_length=50)),
                ('potencia_compactacion', models.CharField(max_length=50)),
                ('kilowatts', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipocompactacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cortadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipocorte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Demoledor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('tamaño', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipodemoledor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elevacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('altura', models.CharField(max_length=50)),
                ('uso', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipoelevacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposEspeciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('caracteristicas_especiales', models.TextField()),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipoequiposespeciales')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('uso', models.CharField(max_length=50)),
                ('kilowatts', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipogenerador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mezcla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipomezcla')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vibrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustible', models.CharField(choices=[('Diesel', 'Diesel'), ('Bencina', 'Bencina'), ('Eléctrico', 'Eléctrico')], max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacidad', models.CharField(max_length=50)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inicio.producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inicio.tipovibrador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
