# Generated by Django 5.1.4 on 2025-01-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='combustible',
            field=models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Eléctrico', 'Eléctrico')], default='Gasolina', max_length=20),
        ),
    ]
