# Generated by Django 5.1.4 on 2025-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_producto_combustible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible'), ('En arriendo', 'En arriendo'), ('Para Importar', 'Para Importar')], default='Disponible', max_length=20),
        ),
    ]
